### ISSUE TITLE
Exported files don't slice

### ISSUE THREAD

**Issue by ixd-hof** [nervoussystem/OBJExport#2]
I just tried to print a model exported with OBJExport. Unfortunately it does not slice in MakerWare and ReplicatorG. I can't figure out why. Even a simple box doesn't slice.

Have you managed printing an exported model?

It seems like the faces are inverted:
![screen shot 2013-05-04 at 16 45 04](https://f.cloud.github.com/assets/2656018/462617/6291663e-b4c9-11e2-952f-245de9b15f8e.png)
![screen shot 2013-05-04 at 16 45 11](https://f.cloud.github.com/assets/2656018/462619/672f9580-b4c9-11e2-8631-7a6d34639d55.png)

**Comment by nervoussystem** [comment]
Yes, the mesh is inverted. The orientation depends entirely on ordering of the vertices when drawn, which is independent of the library. Have you tried inverting the mesh so it is correctly oriented?

**Comment by ixd-hof** [comment]
This example exports a simple box(100, 100, 100); from Processing. I think there's no way of inverting primitives in Processing, right? It would be possible when drawing the box' vertices "by hand".

Inverting the exported model in Meshlab works.

**Comment by cansik** [comment]
I found out that the problem is not the culling itself. If you invert the faces in Meshlab, you get a result which is working, but the model is still flipped.

So to really fix the model after exporting with this library, you have to run `Transform Flip` and flip the `Y-axis`. This results in correct culling and correct model orientation.

I post this just to give other the hint.
